services:
  
  postgresql:
    container_name: postgresql-${NAME_PROJECT}
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./../storage/postgresql_data:/var/lib/postgresql/data
    networks:
      - notificationservice_backend

volumes:
  postgresql_data:

networks:
  notificationservice_backend:
    external: true

