services:

  zookeeper:
    container_name: zookeeper-${NAME_PROJECT}
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - hyperfservice_backend

networks:
  hyperfservice_backend:
    external: true
