services:
  
  kafka:
    container_name: kafka-${NAME_PROJECT}
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092,OUTSIDE2://localhost:9094
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092,OUTSIDE2://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,OUTSIDE2:PLAINTEXT
      KAFKA_CREATE_TOPICS: ${KAFKA_CREATE_TOPICS}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_JMX_USERNAME: ${KAFKA_JMX_USERNAME}
      KAFKA_JMX_PASSWORD: ${KAFKA_JMX_PASSWORD}
    networks:
      - hyperfservice_backend

networks:
  hyperfservice_backend:
    external: true
