services:
  
  clickhouse:
    container_name: clickhouse-${NAME_PROJECT}
    image: bitnami/clickhouse:latest
    ports:
      - "8123:8123"
      - "9005:9912"
    environment:
      CLICKHOUSE_TCP_PORT: 9912
      CLICKHOUSE_ADMIN_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_ADMIN_PASSWORD: ${CLICKHOUSE_PASSWORD}
    networks:
      - hyperfservice_backend

networks:
  hyperfservice_backend:
    external: true
